spring.application.name=backend-java
server.port=8080

# Google OAuth2 credentials - get these from Google Cloud Console
# https://console.cloud.google.com/apis/credentials
spring.security.oauth2.client.registration.google.client-id=86441117376-nssqp91r0q70b3rt0prplem6f7bj45in.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Ollama Configuration
# spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.base-url=http://172.31.35.65:11434
spring.ai.ollama.chat.options.model=gemma4:e2b

# File Upload Limits (for large PDFs)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB